@{
    RootModule           = 'Aundy.DevShell.psm1'
    ModuleVersion        = '0.4.0'
    GUID                 = '4e47345f-a037-4c98-a7c4-2152cc51e80e'
    Author               = 'Aundy.DevShell contributors'
    CompanyName          = 'Aundy'
    Copyright            = '(c) Aundy.DevShell contributors. All rights reserved.'
    Description          = 'A reusable PowerShell developer toolkit for Azure, .NET, DevOps, Git, and local AI workflows.'
    PowerShellVersion    = '7.6'
    CompatiblePSEditions = @('Core')
    RequiredModules      = @()
    FunctionsToExport    = @(
        'Backup-DevEnvironment'
        'CBI'
        'CE'
        'Clear-GitWorkspace'
        'Clear-ProjectWorkspace'
        'CodeCleanest'
        'Common'
        'Connect-BoqDevVm'
        'DenovoBank'
        'Elevate-Shell'
        'Enable-DevShellPromptRefresh'
        'Get-DevShellSettings'
        'Get-DevShellCommands'
        'Get-DevWorkflow'
        'Get-DevContext'
        'Get-DevLocation'
        'Get-Workspace'
        'Get-WorkspaceProjects'
        'Get-WorkspaceRepositories'
        'Get-WorkspaceSolutions'
        'GroupServices'
        'Get-DevShellPrompt'
        'Get-DevShellPromptStyle'
        'Get-DevShellPromptStyles'
        'Get-PublicIp'
        'Initialize-DevShellProfile'
        'Initialize-Themes'
        'Install-AzureDeveloperTools'
        'Install-CodeExtensions'
        'Install-Communication'
        'Install-DeveloperTools'
        'Install-Entertainment'
        'Install-Environment'
        'Install-Linux'
        'Install-Package'
        'Install-Productivity'
        'Install-SqlServer'
        'Install-Utilities'
        'Install-VisualStudio'
        'Invoke-ClaudeApi'
        'Invoke-ClaudeLocal'
        'Invoke-ReloadProfile'
        'Invoke-Tests'
        'Invoke-DevWorkflow'
        'New-DockerDatabaseServer'
        'New-DevShellPromptTheme'
        'Open-Code'
        'Open-CurrentDirectory'
        'Open-Repository'
        'PaymentsDomain'
        'Personal'
        'Push-Folder'
        'Push-Work'
        'Reload-Profile'
        'Remove-BuiltInPester'
        'Reset-GitConnection'
        'Resolve-DevWorkflow'
        'Restart-Shell'
        'Set-SqlServerFirewallRule'
        'Set-DevShellPromptStyle'
        'Set-DevLocation'
        'ServiceFabric'
        'SharedDomain'
        'Show-DevShellDiagnostics'
        'Show-DevShell'
        'Show-DevShellPrompt'
        'Show-DevContext'
        'Show-Workspace'
        'Start-Azurite'
        'Templates'
        'Test-Administrator'
        'Test-DevWorkflow'
        'Test-DevShell'
        'Tools'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @('reload', 'rshell', '.code', '.codecleanest', 'dev')
    PrivateData          = @{
        PSData = @{
            Tags       = @('PowerShell', 'Developer', 'Azure', 'Git', 'DevOps', 'Ollama')
            LicenseUri = 'https://github.com/aundykmahesh/Aundy.DevShell/blob/main/LICENSE'
            ProjectUri = 'https://github.com/aundykmahesh/Aundy.DevShell'
        }
    }
}
