name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate module package
        shell: pwsh
        run: Test-ModuleManifest ./src/Aundy.DevShell/Aundy.DevShell.psd1
      - name: Upload module artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aundy.DevShell
          path: src/Aundy.DevShell
